name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Create directory
        run: |
          mkdir -p out/assets

      - name: Copy resources
        run: |
          cp -r src/minecraft/assets/* out/assets/

      - name: Extract client libs
        run: |
          find libs/client -name "*.jar" -exec unzip -qn {} -d out/ \;

      - name: Compile sources
        run: |
          javac -cp "libs/client/*:libs/minecraft/*" \
          -d out \
          -sourcepath src/minecraft \
          $(find src/minecraft -name "*.java")

      - name: Package JAR
        run: |
         jar cf Loftily.jar -C out .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Loftily
          path: |
            ${{ github.workspace }}/Loftily.jar
            ${{ github.workspace }}/Loftily.json