name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Prepare artifact folder
        run: |
          mkdir -p Loftily
          cp app/build/libs/*.jar Loftily/
          cp Loftily.json Loftily/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Loftily
          path: Loftily/
